apiVersion: apps/v1
kind: Deployment
metadata:
  name: docgen
  namespace: bots
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docgen
  template:
    metadata:
      labels:
        app: docgen
    spec:
      containers:
      - name: docgen
        image: ghcr.io/lesso/docgen:latest        # <-- use your built image
        ports:
        - containerPort: 8000
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: docgen-minio
              key: rootUser
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: docgen-minio
              key: rootPassword
        - name: MINIO_BUCKET
          value: lesso-docgen
        - name: MINIO_ENDPOINT
          value: https://miniofiles.lesso.co.uk
---
apiVersion: v1
kind: Service
metadata:
  name: docgen
  namespace: bots
spec:
  type: ClusterIP
  selector:
    app: docgen
  ports:
  - port: 80          # the port n8n will call
    targetPort: 8000  # the port the container exposes

